### ISSUE TITLE
フッターのデザインを変更したい

### ISSUE THREAD

**Issue by haniwaman** [okutani-t/git-study#9]
## フッターを以下のとおり変更するのはどうでしょうか？

* 背景色：#999（幅は画面いっぱいに）
* 文字色：#fff
* テキスト：右寄せ
* 余白を少なく

## ScreenShot

現状はこんな感じです。

![image](https://user-images.githubusercontent.com/32994211/37866371-552018ea-2fcd-11e8-9158-92548dca165a.png)

**Comment by okutani-t** [comment]
いいですね！

オシャレになりそうです 👍
